import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import InstagramIcon from "@mui/icons-material/Instagram";
import GitHubIcon from "@mui/icons-material/GitHub";
import TwitterIcon from "@mui/icons-material/Twitter";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import { services } from "../component/card";
import Card from "../component/cardlayout";

export default function Home() {
  return (
    <div className="">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <section>
        <div className="container mx-auto  grid md:grid-cols-12 sm:md:grid-cols-2  mt-80">
          <div className="md:col-span-6 my-auto">
            {/* <div className=' bg-white'> ddd</div> */}
            <p className=" font-medium text-[8px] tracking-[1em] text-[#656D72]">
              MY NAME IS
            </p>
            <div className="pt-4 w-auto ">
              <span className="text-[#F1F1F1] font-medium text-6xl">Caleb</span>
              <span className="text-[#7E74F1] text-6xl font-medium">
                {" "}
                Nyong.
              </span>
            </div>
            <div className="mt-6 md:w-96 sm:w-auto">
              <p className="text-[#F1F1F1] text-sm">
                Creative front-end developer with more than +2 years of
                experience in enterprise companies and startups. Proficient in
                Html, Tailwind Css, Javascript and React. Passionate about UI/UX
              </p>
            </div>
            <div className="text-white container flex gap-3 pt-4">
              <InstagramIcon />
              <GitHubIcon />
              <TwitterIcon />
              <LinkedInIcon />
            </div>
          </div>

          <div className="md:col-span-6 sm:order-last">
            <img src="/img/img1.png" className="w-[100%] h-auto bg-cover" />
          </div>
        </div>
      </section>
      <section className="container mx-auto mt-28 ">
        <div>
          <p className=" flex justify-center font-medium text-[8px] tracking-[1em] text-[#656D72]">
            SERVICES
          </p>

          <h1 className="flex justify-center text-white font-bold text-center">
            SPECIALIZED IN
          </h1>
        </div>

        <Card services={services} />
      </section>
    </div>
  );
}

// export const services = [
//   {
//     _id: "1",
//     icon: (
//       <svg
//         xmlns="http://www.w3.org/2000/svg"
//         fill="none"
//         viewBox="0 0 24 24"
//         stroke-width="1.5"
//         stroke="currentColor"
//       >
//         <path
//           stroke-linecap="round"
//           stroke-linejoin="round"
//           d="M12 9.75v6.75m0 0l-3-3m3 3l3-3m-8.25 6a4.5 4.5 0 01-1.41-8.775 5.25 5.25 0 0110.233-2.33 3 3 0 013.758 3.848A3.752 3.752 0 0118 19.5H6.75z"
//         />
//       </svg>
//     ),
//     title: "UI/UX Design",
//     detail:
//       "Turn what you have in mind of a digital product into reality. For any platform you consider.",
//   },
//   {
//     _id: "2",
//     icon: (
//       <svg
//         xmlns="http://www.w3.org/2000/svg"
//         fill="none"
//         viewBox="0 0 24 24"
//         stroke-width="1.5"
//         stroke="currentColor"
//       >
//         <path
//           stroke-linecap="round"
//           stroke-linejoin="round"
//           d="M12 9.75v6.75m0 0l-3-3m3 3l3-3m-8.25 6a4.5 4.5 0 01-1.41-8.775 5.25 5.25 0 0110.233-2.33 3 3 0 013.758 3.848A3.752 3.752 0 0118 19.5H6.75z"
//         />
//       </svg>
//     ),
//     title: "Application Development",
//     detail:
//       "Standard designing, building, and implementing your applications with documentation.",
//   },
//   {
//     _id: "3",
//     icon: (
//       <svg
//         xmlns="http://www.w3.org/2000/svg"
//         fill="none"
//         viewBox="0 0 24 24"
//         stroke-width="1.5"
//         stroke="currentColor"
//       >
//         <path
//           stroke-linecap="round"
//           stroke-linejoin="round"
//           d="M12 9.75v6.75m0 0l-3-3m3 3l3-3m-8.25 6a4.5 4.5 0 01-1.41-8.775 5.25 5.25 0 0110.233-2.33 3 3 0 013.758 3.848A3.752 3.752 0 0118 19.5H6.75z"
//         />
//       </svg>
//     ),
//     title: "Web Development",
//     detail:
//       "Create and maintain your websites and also take care of its performance and traffic capacity.",
//   },
// ];
